export const FETCH_LEAGUES_REQUEST = 'FETCH_LEAGUES_REQUEST'; 
export const FETCH_LEAGUES_FAILURE = 'FETCH_LEAGUES_FAILURE'; 
export const LEAGUES_KEY = 'LEAGUES_KEY'; 
export const LEAGUES_NAME = 'LEAGUES_NAME';
export const LEAGUES_COUNTRY = 'LEAGUES_COUNTRY'; 

export const LEAGUE_KEY_CHOSEN = 'LEAGUE_KEY_CHOSEN'; 
