export const FETCH_LEAGUES_REQUEST = 'FETCH_LEAGUES_REQUEST'; 
export const FETCH_LEAGUES_FAILURE = 'FETCH_LEAGUES_FAILURE'; 

export const LEAGUE_DATA = 'LEAGUE_DATA'; 

export const LEAGUE_KEY_CHOSEN = 'LEAGUE_KEY_CHOSEN'; 
