export const FETCH_DM_REQUEST = 'FETCH_DM_REQUEST'; 
export const FETCH_DM_FAILURE = 'FETCH_DM_FAILURE'; 
export const DM_HOME_TEAM = 'DM_HOME_TEAM'; 
export const DM_AWAY_TEAM = 'DM_AWAY_TEAM'; 

export const DM_HOME_TEAM_SCORE = 'DM_HOME_TEAM_SCORE'; 
export const DM_AWAY_TEAM_SCORE = "DM_AWAY_TEAM_SCORE"; 

export const DM_HOME_TEAM_LOGO = 'DM_HOME_TEAM_LOGO'; 
export const DM_AWAY_TEAM_LOGO = 'DM_AWAY_TEAM_LOGO'; 
