export const FETCH_TEAMS_REQUEST = 'FETCH_TEAMS_REQUEST'; 
export const FETCH_TEAMS_FAILURE = 'FETCH_TEAMS_FAILURE'; 

export const TEAM_DATA = 'TEAM_DATA'; 

export const TEAM_INDEX = 'TEAM_INDEX';
export const TEAM_SEARCH_RESULTS = 'TEAM_SEARCH_RESULTS'; 
