export const LEAGUE_CONTENT_REQUEST = 'LEAGUE_CONTENT_REQUEST'; 
export const LEAGUE_CONTENT_FAILURE = 'LEAGUE_CONTENT_FAILURE'; 
export const LEAGUE_NAME = 'LEAGUE_NAME'; 
export const LEAGUE_AREA_NAME = 'LEAGUE_AREA_NAME'; 
export const LEAGUE_YEAR = 'LEAGUE_YEAR'; 

export const LEAGUE_TEAM_ID = 'LEAGUE_TEAM_ID'; 
export const LEAGUE_TEAM_NAME = 'LEAGUE_TEAM_NAME';
export const LEAGUE_TEAM_LOGO = 'LEAGUE_TEAM_LOGO'; 

export const LEAGUE_PLAYER_ID = 'LEAGUE_PLAYER_ID'; 
export const LEAGUE_PLAYER_NAME = 'LEAGUE_PLAYER_NAME'; 
export const LEAGUE_PLAYER_LOGO = 'LEAGUE_PLAYER_LOGO'; 
export const LEAGUE_PLAYER_NATIONALITY = 'LEAGUE_PLAYER_NATIONALITY'; 

export const LEAGUE_PLAYER_SEARCH_INDEX = 'LEAGUE_PLAYER_SEARCH_INDEX'; 
