export const LEAGUE_CONTENT_REQUEST = 'LEAGUE_CONTENT_REQUEST'; 
export const LEAGUE_CONTENT_FAILURE = 'LEAGUE_CONTENT_FAILURE'; 

export const LEAGUE_DATA = 'LEAGUE_DATA'; 

export const LEAGUE_PLAYER_SEARCH_INDEX = 'LEAGUE_PLAYER_SEARCH_INDEX'; 
